#-------------------------------
# General Site Settings
title: Pegasus Hacker
logo: logo.svg # You can add own logo.
description: All About Hacking


#-------------------------------
# Author Settings
author:
  name: Muhammad Sobri Maulana
  image: 01.jpg
  say-hello: Hello, Iâ€™m <strong> Doctor Sobri</strong>
  bio: Designs, talks, and writes about <strong>Hacking</strong>, <strong>Medical Technology</strong>, <strong>Spy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">money</a> & develop business.


#-------------------------------
# Contact links
twitter: https://twitter.com/muhsobrimaulana1
facebook: https://facebook.com/muhammadsobrimaulana
dribbble: https://dribbble.com/muhammadsobrimaulana
instagram: https://instagram.com/muhammad_sobri_maulana
pinterest: https://pinterest.com/muhammadsobrimaulana


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: muhammadsobrimaulana # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: muhammad_sobri_maulana # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
